import Head from "next/head";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Cv from "../components/Cv/Cv";
import Footer from "../components/Footer/Footer";
import Navigation from "../components/Navigation/Navigation";
import Work from "../components/Wok/Work";
import styles from "../styles/Index.module.css";

export default function Home() {
  return (
    <div className={styles.site}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic&display=optional"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700,700italic,900,900italic&display=optional"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <Navigation />
      <main className={styles.main}>
        <About />
        <Work />
        <Cv />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
